spring.application.name=dent

spring.datasource.url=jdbc:postgresql://localhost:5432/dent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=4gS9N9aF2dKpXJdQeSp9RmF5p8VtU4fB7QeL3WmM6BzN2QhH8JtP9FsG7DxA8Kj
